### ISSUE TITLE
Add twitch viewer count and subs to task bar

### ISSUE THREAD

**Issue by ed-fish** [stuck-overflow/dotfiles#1]
As discussed on Discord it would be cool if we could show the number of viewers and subscribers in the task bar while we stream.

**Comment by satu** [comment]
Viewer count done. We need to use a `UserToken` instead of `AppAccessToken` to access subs data.

**Comment by satu** [comment]
(also we should have followers number, latest follower, latest subscriber, financial data?)

also surface title (maybe cropped at 20 chars)

**Comment by satu** [comment]
Resolved by #13
