### ISSUE TITLE
Throttle the HTTP requests of the widgets

### ISSUE THREAD

**Issue by satu** [stuck-overflow/dotfiles#20]
The twitch widget and the weather one make HTTP requests at every refresh of the status bar.

The refresh of the status bar happens once a second, and we can't change that without impacting the sheer beauty of our tomato timer widget.

Therefore we need a solution to limit the HTTP requests going out while still preserving the functionality. A quick idea would be to wrap these widget in a script that stores the time of the last execution and the last output, and only executes a command if enough time has passed from the last run.

We could use Rust for the lols, but frankly something simpler would work too.

**Comment by LordMZTE** [comment]
We should consider porting these widgets to rust. That would make it a lot easier to implement this.

**Comment by satu** [comment]
twitch widget is already Rust: https://github.com/stuck-overflow/dotfiles/tree/main/twitch-tmux-widget

You are right it would be quite easy to implement the throttling in the widget.

**Comment by satu** [comment]
After chatting with @rexroof he pointed out the following part of the documentation:


> In addition, the last line of a shell command's output may be inserted using ‘#()’.  For example, ‘#(uptime)’ will insert the system's uptime.  When con‐
>      structing formats, tmux does not wait for ‘#()’ commands to finish; instead, the previous result from running the same command is used, or a placeholder
>      if the command has not been run before.  If the command hasn't exited, the most recent line of output will be used, but the status line will not be up‐
>      dated more than once a second.  Commands are executed with the tmux global environment set (see the GLOBAL AND SESSION ENVIRONMENT section).

it's then sufficient to add a `; sleep XX` to each command.
